### ISSUE TITLE
Why is magic a required attribute?

### ISSUE THREAD

**Issue by pgleeson** [AllenInstitute/sonata#105]
The documentation requires~:
```
Each h5 file must contain the following two top level attributes:

    version A 2-element uint32 dataset containing the spec version which the file conforms.
    magic A uint32 with the value 0x0A7A

```
Why is magic required? Seems quite arbitrary...

**Comment by hernando** [comment]
It's totally arbitrary, as all conventions. Since SONATA files can't be easily distinguished from any random H5 file, this was added as a quick way to detect bad files. It's inspired in the signature that many file formats specify similarly: https://en.wikipedia.org/wiki/List_of_file_signatures.

**Comment by pgleeson** [comment]
Thanks. I suppose it's nothing that can't be solved with a quick web search...
