### ISSUE TITLE
Missing `id` in all nml files of examples/nml

### ISSUE THREAD

**Issue by asanin-epfl** [AllenInstitute/sonata#108]
Hi! All `nml` files in examples currently miss `id` attribute for tags: `specificCapacitance` and `resistivity`. When I manually add `id`, I'm able to transform them by BluePyOpt. Would it be ok to add those `id` here?

**Comment by pgleeson** [comment]
Are you referring to the files in here: https://github.com/AllenInstitute/sonata/tree/master/examples/shared_components/biophysical_neuron_templates/nml?

There are multiple validity issues with those files and they shouldn't be considered as "NeuroML files" less so "NeuroML cell files". They're snippets of NeuroML used internally by Sonata readers to get combined with hoc/swc to make executable Neuron cell models. This is a rather adhoc pipeline (one long term solution is to allow full specification of the cell model in NeuroML and/or PyNN formats). Nevertheless, the changes you suggest could be made as long as they are tested with BMTK (and ideally NetPyNE, see for ex https://github.com/AllenInstitute/sonata/issues/74), to make sure they give the same results.

**Comment by asanin-epfl** [comment]
> Are you referring to the files in here: https://github.com/AllenInstitute/sonata/tree/master/examples/shared_components/biophysical_neuron_templates/nml?

Yes

Thank you for the info.
