### ISSUE TITLE
No presynaptic section ID / section distance specified in the reserved edges attributes 

### ISSUE THREAD

**Issue by arsenius7** [AllenInstitute/sonata#12]
As far as I can see, we have only postsynaptic (i.e. target) `sec_id` and `sec_x`.
Is it intentional?
Up to my knowledge, "path position" on the axon is used for some morphological analysis (so `delay` won't suffice).

**Comment by hernando** [comment]
Edges  (and nodes) attributes are not limited to reserved optional attributes. Users are free to add whatever they need for a particular applications.
sec_x may be the path position that you're looking for, but it depends on whether you're referring to a distance to soma (which is what I would call the path distance) or the distance to the beginning of the section.

**Comment by arsenius7** [comment]
> sec_x may be the path position that you're looking for

It's the path position on _postsynaptic_ neuron (on dendrite, roughly speaking), while sometimes we need it on _presynaptic_ one (on axon).

The thing is, if we reserve a optional pair of attributes for postsynaptic view, we'd better do it for presynaptic one, as is done with xyz-positions (`afferent_center_position` + `efferent_center_position`).

**Comment by hernando** [comment]
I missed your actual point (pre vs post) and what confused by the path term.
You're right it's an important omission that I didn't notice before, it should be added, but then the existing attributes must be renamed to source_sec_id, source_sec_x to add target_sec_id and target_sec_x. I also don't like very much referring to sections here (I already had a similar discussion for the compartment report mapping), I would prefer the names to be source_element_id and source_element_pos

**Comment by arsenius7** [comment]
Just out of curiosity, what is the problem with `section`s?
IMHO, at this level (when we already assume that edge is not just an abstract "edge", but an apposition between two detailed morphologies) it's not needed to cling to abstract terms like "edge" or "element" anymore, and using the established jargon would serve better.
Don't have a strong opinion here, however.

**Comment by hernando** [comment]
The point is that and edge is connecting two nodes, and the nodes can be whatever makes sense for the simulator. If you have multiple edges between to nodes, the node elements being connecting are morphological sections in the case of biophysical models. But for other models it could mean something else. I just favor element over section to not make assumptions that would end up in abusing a dataset that has the appropriate type to store something semantically different or having a proliferation of very similar datasets that just differ in the name, but not the intent or data type.

**Comment by hernando** [comment]
@arsenius7 any opinion about the suggested renaming or shall I close this ticket and make no further changes?

**Comment by hernando** [comment]
Closing without applying further changes.
