### ISSUE TITLE
Rotation angles are intrinsic or extrinsic?

### ISSUE THREAD

**Issue by hernando** [AllenInstitute/sonata#14]
From the description of rotation_angle_{x,y,z}axis is not clear whether each rotation in the sequence is referred to the world coordinate axes (extrinsic) or the local ones (intrinsic). Can anybody clarify this?
For understanding the difference between both check: https://en.wikipedia.org/wiki/Euler_angles#Definition_by_intrinsic_rotations.

**Comment by hernando** [comment]
It's a bit dangerous to infer expected behavior from observations though. We could be basing the spec in a buggy implementation. I will follow your advice when the time comes and create a PR to document it, I hope interested people reacts to that one.

**Comment by CellAssembly** [comment]
Our coordinate axes at AIBS are fixed. The rotation order still matters (not-commutative) but our axes never change which means extrinsic according to the wikipedia link.
