### ISSUE TITLE
components_dir or components?

### ISSUE THREAD

**Issue by hernando** [AllenInstitute/sonata#18]
In the spec, the name of the section from the circuit configuration json with paths to different circuit elements is called components_dir, but the json from the example provided by the Allen Institute contains components.
Which one should be accepted as correct? (By the way, I prefer "components")

**Comment by kaeldai** [comment]
Either one works with me. In the documentation from the shared drive it's "components" and seems to have been changed to "components_dir" when migrated to github.

**Comment by hernando** [comment]
I don't see "components" anywhere in the shared google doc...
Anyway I will replace compoenents_dir with components everywhere.
