### ISSUE TITLE
Defining dL

### ISSUE THREAD

**Issue by wvangeit** [AllenInstitute/sonata#22]
The simulation config file contains a parameter 'dL'.
Could some exact explanation be provided on how that's being used in the ABI simulations.
(As far as I understood it is used to split sections into compartments)

Not sure if it's necessary to specify this also in the SONATA description document (it is part of the example simulation config in the document).

**Comment by wvangeit** [comment]
So if I understand things correctly, nseg is set to:
section.nseg = 1 + 2 * int(section.L / (2*dL))

Can you confirm ?

**Comment by hernando** [comment]
Has this issue been address off-line?

**Comment by wvangeit** [comment]
It's best that @kaeldai confirms the above equation is correct.

**Comment by kaeldai** [comment]
@wvangeit - The formula you gave is the way we set number of segments for biophysically detailed cell. It is the formula that was used to optimize parameters for the cell models in the Allen Cell Types Database.

**Comment by kaeldai** [comment]
closing as this is replicated and should be fixed in issue #52
