### ISSUE TITLE
morphology_file error in examples

### ISSUE THREAD

**Issue by wvangeit** [AllenInstitute/sonata#29]
When running the 9-cell and 300-cell examples with bmtk one gets:
KeyError: 'Unknown property morphology_file'

For now this can be fixed by opening the node types csv file and changing the 'morphology' column name to 'morphology_file'

Not sure if this has to be fixed in the example or in bmtk

**Comment by hernando** [comment]
In bmtk. We agreed to change the spec to be morphology. @kaeldai Could you please update bmtk, or can you create the PR yourself @wvangeit?

**Comment by kaeldai** [comment]
I will try fixing it in the next day or two and recreate the example (we are a little swamped with csn prep and everything). There are a number of other parameters that have changed since I built those networks which I will also try to update.

**Comment by hernando** [comment]
I'm closing this as the examples are all consistent with the spec. @wvangeit, if necessary open a ticket in bmtk.
