### ISSUE TITLE
How are pre & post populations in edges specified?

### ISSUE THREAD

**Issue by pgleeson** [AllenInstitute/sonata#43]
There needs to be a unique way to specify the pre and post populations (within which the node_ids are unique) as used in edges. For example this: https://github.com/AllenInstitute/sonata/blob/master/examples/9_cells/network/inhvirt_cortex_edges.h5 is clearly from pop **inhvirt** to pop **cortex**, but nowhere are those specified apart from the name of the file and the hdf5 group name **inhvirt_to_cortex**. Relying on successful parsing of that string is not ideal (e.g. a population might be called **input_to_cortex**).

**Comment by kaeldai** [comment]
In the edges files both the source_node_id and target_node_id datasets should have a "node_population" attribute to indicate their respective nodes. It's mentioned in the documentation but a bit hidden, we can probably do a better job of clarifying the meta-data attributes.

**Comment by pgleeson** [comment]
Ok, thanks. It's a bit hard to find as there are not many other attributes used, but it's good that it's there.
