### ISSUE TITLE
Can we change cell orientations in the 300 cell example without modifying anything else?

### ISSUE THREAD

**Issue by hernando** [AllenInstitute/sonata#48]
I'd like to change the orientation of the cell in the 300 cell example to not be random because visually it doesn't look very appealing. I wonder whether this could have any side effect on the synapses for example. Otherwise, I'd propose a PR with a new orientation.

**Comment by kaeldai** [comment]
I've looked and for the 300 cell example network the rotation_angle's are not used to determine synaptic location or strength. There values should have no impact on the simulation. You could go ahead and just change their values in nodes.h5 file. But if you do let me know what function/range of values you are using and I will update the build_network.py script (otherwise next time some-one tries to build the example the orientations will be random again).

**Comment by hernando** [comment]
I can update and run the script myself as well, actually I prefer this.
I installed bmtk and tried to run the current script, but I have an error importing SWCReader from swc_reader. Where does this package come from?

**Comment by kaeldai** [comment]
Hi @hernando, can you send me the error message you're getting.

**Comment by kaeldai** [comment]
Oh wait, I just realized that you may be using Python 3. In which case bmtk/builder/bionet/__init__.py the line
```python
from swc_reader import SWCReader
```
should use a relative import (using a **.**)
```python
from .swc_reader import SWCReader
```
I will go ahead and update the develop branch. Apparently pylint doesn't check for broken imports so now I'm wondering what else isn't py3 compliant.

**Comment by hernando** [comment]
Thanks for the hint, now I get an import error from swc_reader.py trying to import neuron. I guess that I can't avoid having to install/compile NEURON, right?

**Comment by hernando** [comment]
This is not as simple as I thought... I was looking at the morphologies too see what is the rotation that I should apply and then I saw that their orientations are not normalized to any particular local reference frame. Would it be OK if we modify the SWC files to recenter and reorient the 5 morphologies in there?

**Comment by hernando** [comment]
Done
