### ISSUE TITLE
'morph_translate' description is misleading

### ISSUE THREAD

**Issue by arsenius7** [AllenInstitute/sonata#5]
At the moment 'morph_translate' attribute is described as
> morph_translate - Optional reserved attribute, if the value is set to 0, the translation operations described above are not applied.

Combined with the section above describing all the transformations done to the cell position / orientation, this made me think that _none_ of the translations are applied.

As @hernando clarified though, it is relevant for re-centering only.
If we need this attribute at all, we should rename it and update the description.

**Comment by hernando** [comment]
The description should be more self contained and only refer to another text section for details. If the reference is maintained it should be a hyperlink, otherwise it's hard to find without having read the whole document.

**Comment by arsenius7** [comment]
Yes, #11 PR kind of "addresses" it.
Perhaps we'll need to revise it eventually, but this thread could be closed for now.
Thanks all.
