### ISSUE TITLE
edges sec_id from swc file?

### ISSUE THREAD

**Issue by salvadord** [AllenInstitute/sonata#53]
In the edges file there is a parameter 'sec_id' which I assumed was the index of the postsynpatic section -- is this right? if so, is there an easy way to obtain this id from the swc file? I'm currently reading the swc morphology using NEURON's h.Import3d_SWC_read() and h.Import3d_GUI, and then importing that into NetPyNE.

**Comment by wvangeit** [comment]
@salvadord the NEURON import3d code normally creates a list 'all' in the template of the cell. The secid is the index in that sectionlist.

**Comment by hernando** [comment]
@salvadord do you have all the answers? Can we close this issue?

**Comment by salvadord** [comment]
Ok, thanks, I will use the index from the 'all' list of import3d
