### ISSUE TITLE
Can membrane potential be recorded when a cell is of type point_process?

### ISSUE THREAD

**Issue by pgleeson** [AllenInstitute/sonata#55]
If I have a population where the cells are point_process, it should be possible to record the membrane potential (in order to check the sub threshold v in addition to saving spikes). I've tried this:

```
  "reports": {
    "membrane_potential": {
      "cells": "point_nodes",
      "variable_name": "v",
      "module": "membrane_report",
      "sections": "soma"
    }
  }
```
with an entry in node_sets.json:
```
{
  "point_nodes": {
    "model_type": "point_process"
  }
}
```

and it does save a output/membrane_potential.h5, but the data array is empty

Code for this model here: https://github.com/pgleeson/sonata/tree/intfire/examples/small_intfire

**Comment by hernando** [comment]
Shouldn't this ticket go to another repository?
By the way, as per #33 point_process is going to be renamed to point_neuron. I don't know if this change will be done in coordination with other tools.

**Comment by pgleeson** [comment]
I agree it may be related to BMTK, but it probably should be raised here, as the reports block is part of the spec, and it's relevant for the examples included for Sonata.

I did try "variable_name": "m", as suggested by the Neuron docs on IntFire1, but that didn't work. https://www.neuron.yale.edu/neuron/static/docs/help/neuron/neuron/mech.html#IntFire1.

This is probably related to the bigger issue of allowing (and using in standard examples) simulator specific cell types, e.g. for a NEST simulation the line will be: "variable_name": "V_m" as [here](https://github.com/AllenInstitute/bmtk/blob/develop/docs/examples/point_120cells/config.json#L29).

Moving to PyNN or NeuroML based cell definitions in the longer term will help address this issue.

**Comment by kaeldai** [comment]
I can confirm that in the bmtk we don't record cell variables of NEURON's intfire cells, and just skip those cells without warning. We can add recording of intfire cells, it's just something no one yet had asked for. 

I like the idea of adding a dictionary of terms for specifying attributes like voltage, calcium, etc. And I'd prefer to use that which has already been done in NeuroML2 or PyNN. I'd suggest we create a new enhancement request for SONATA, and move this bug to the bmtk repo. However in the short term I'd recommend we can add language suggesting that a given implementation give a warning and/or exit out if the user tries to report on a cell variable that doesn't exists.

**Comment by pgleeson** [comment]
No longer relevant as nrn:IntFire1is fundamentally tied to an inbuilt Neuron artificial cell...

It should be possible to record v from an I&F cell when https://github.com/AllenInstitute/sonata/issues/91 is implemented
