### ISSUE TITLE
Specify rotations using quaternions (or improve the current formalism)

### ISSUE THREAD

**Issue by hernando** [AllenInstitute/sonata#57]
In the current spec, rotations are specified using a very unintuitive formalism (extrinsic rotations around z, y, x angles). The original intention was to use Euler angles, but this formalism is not proper Euler angles, as in Euler angles the first and third rotation angles are always the same. Instead, what we have is Tait–Bryan angles, but not the widely used heading(yaw)-pitch-roll(bank), which use intrinsic rotations.

The problems of the chosen approach are three:
1. There's **no convention for the orientation of morphologies** (e.g. apical dendrite along z axis and planar cells extended on the xy plane). The lack of this convention defeats completely the purpose of having rotation angles. The spec encourages having morphologies in a standarized orientation, but it doesn't say which it should be to benefit from the rotation formalism.
2. Assuming there was a convention for morphology orientation, **the chosen formalism is not intuitive**.  It could make sense if apical dendrites were oriented along the z axis, but with the extrinsic rotation around the x axis at the end, describing a pose is not straightforward anymore. This problem is not present in common formalisms like 
3. To further complicate things, the local to global transformation is easy to apply, but **given an arbitrary rotation matrix, its decomposition into the three extrinsic rotations angles is not simple** and the formula is not included anywhere in the spec. In the highly probable situation of having orientations derived from a data driven approach, the task of converting whatever representation into the required one becomes an error prone non trivial task for which users are on their own.

I consider this a defect in the spec for which I propose the following solutions:
* Change orientations to use quaternions representing the local to global transform.
Pros: univocal representation, more compact that a full 3x3 rotation matrix, widely used in computer graphics and engineering, reduces specification complexity.
Cons: introduces the first non-scalar attribute in the spec, increases the storage requirements when only one rotation angle is needed, it has one redundant component (although assuming normalization it can be derived from the other three), more disruptive than other alternatives.
* Refine the current formalism: change angles to be to yxy proper Euler and specify the recommended orientation for morphologies to be apical dendrites up y-axis and planar extent on xy plane.
Pros: retains the original spirit of the spec, less disruptive than using a quaternion, angles can still omitted (not many meaningful combinations exist anyway, only y and xy I'd say).
Cons: Doesn't solve problem 3, adds more complexity to the spec,

I guess my preference is clear :)

**Comment by arsenius7** [comment]
To rephrase what said above, using quaternions as the _storage_ format does not oblige us to use them for model building or subsequent usage.

Using rotation angles for model building is deceitfully simple and error-prone.

For subsequent usage, it's unlikely just inspecting the numbers in HDF5 is of much use; to see the rotation most likely we'll have to apply it and visualize the result.

Quaternions can thus serve as least-ambiguous representation. It's perfectly fine to work in Euler angles for building the model, should the author prefer it; and to convert to quaternions as a last step for dumping to SONATA.

**Comment by hernando** [comment]
I have started to modify the spec to add the orientation attribute using quaternions. As discussed elsewhere, the attribute could be non scalar (the first one in the spec) to make it less verbose. This raises two questions:
- Why positions are not scalar as well?
- How do you represent non scalar attributes in node_type.csv files?

For the first question I haven't found any answer so far. For the second one, I would propose to say that multi valued attributes (i.e. arrays) are specified as a list of space separated values and must be quoted with `"` (as specified [here](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#csv) for CSV fields containing spaces).
