### ISSUE TITLE
Consistent approach to storing coordinates

### ISSUE THREAD

**Issue by arsenius7** [AllenInstitute/sonata#68]
According to the spec, cell positions are now stored as `x`, `y`, `z` 1-D attributes; while synapse positions are stored as 2-D attributes (e.g., `afferent_center_position`).

Ideally we should be consistent here.
Imho, storing positions in 2-D attributes makes sense since we usually need all the coordinates; but we need to recall why we decided to go with `x`, `y`, `z` for cell positions recently. :)

**Comment by hernando** [comment]
Nobody seems to recall and after having decided to represent orientation with quaternions, which will probably be stored as a 2-D array with 4 columns, it makes sense to reconsider storing positions in a single dataset again.

**Comment by arsenius7** [comment]
For the moment we decided to get away with 1-D attributes only; and modified the spec for synapse positions accordingly.
