### ISSUE TITLE
Cell location corresponds to soma first 3d point

### ISSUE THREAD

**Issue by salvadord** [AllenInstitute/sonata#79]
In the 300 cell example the PV1 morphology file 3d points are not centered around 0,0,0, so when the PV cells were located in the network it looked like this:

![image](https://user-images.githubusercontent.com/8440562/50936937-b4c7d100-143f-11e9-9400-d7aede83a8da.png)

To fix this, after importing the morphology I normalized all 3d points by subtracting the 1st soma 3d point.

**Comment by salvadord** [comment]
![image](https://user-images.githubusercontent.com/8440562/50938438-2efb5400-1446-11e9-8635-b8d2d659bb36.png)

**Comment by hernando** [comment]
This is by-design. I mean, the spec does not enforce that morphologies have their soma centered at 0, 0, 0, which means that all parsing tools have to do this themselves.
If you find it debatable, I'm more than open to discuss whether the spec should require centered morphologies as there's another feature in the spec which allows disabling morphology recentering in a node basis and it complexifies circuit loading unnecessarily.

**Comment by hernando** [comment]
If you're fine with the current spec, I'll close this issue.
