### ISSUE TITLE
Can node type be omitted?

### ISSUE THREAD

**Issue by arsenius7** [AllenInstitute/sonata#8]
The spec is not clear what should I do if I don't need to use common node types.
Should I define an "empty" node_type in CSV files nevertheless?
Should there be a reserved "no node type id" value?

Finally, if none of nodes defined in HDF5 rely on some node type, is it possible to omit "node_types_file" key in circuit config or set it to NULL?

**Comment by hernando** [comment]
My interpretation of the spec is that node_type_ids is mandatory and every node should have a type id. I find it surprising that you can think of a case in which the node type is not needed at all, could you provide an example?

I have a different concert about the node_types.csv that I've just realized. I will create a separate ticket for it.

**Comment by arsenius7** [comment]
>  I find it surprising that you can think of a case in which the node type is not needed at all, could you provide an example?

The current BBP usecase?
Why would we need node types for it and what node types would it be?

**Comment by hernando** [comment]
Each node type would be an me-type as I understand it, but you should ask Jean-Denis or Eilif for a more concrete example.

**Comment by jdcourcol** [comment]
For the BBP use case and HBP ones, we don't need the node_type_id as we put everything in the h5 file. So if node_type_id is mandatory, we will end up setting a dummy value there.
I am not saying that we may not use that convenience (node_type_id and node_types.csv)  in the future but for the time being it is useless.

**Comment by hernando** [comment]
I was assuming that there are some model parameters (ion channel conductances, axonal delay, ... that you want to assign at the node type level, and not node by node). But even if it's just for the model template, it helps having the node type (which is a number) to point to an entry that contains it rather than having a template name string per node.

**Comment by arsenius7** [comment]
And that's exactly the reason why node types seem suspicious to me.
They give you only _one_ "traits" dimension.
As soon as you'd like to have common parameter A for some node subset and B for another node subset, "node_type" helps no longer (unless you define 'synthetic' types like A x B).

**Comment by arsenius7** [comment]
Can't say I'm quite convinced, but as the discussion is going in circles, there is no reason in persisting it either.
Perhaps once we have more experience with the format, we can come back to this question.
Thanks.
